#!/bin/sh

#Uncompress any Ableton Live set/s
git diff --cached --name-only --diff-filter=ACM | grep .als |

while read set
do
	if file --mime-type "$set"| grep -q gzip$
	then
		gunzip -qS .${set##*.} "$set" &&

		mv "${set%.*}" "$set" && git add "$set"
	fi
done
#-------------------------------------------------------------------------------
